const CREATED_CODE = 201;
const BAD_REQUEST_CODE = 400;
const UNAUTHORIZED_ERROR_CODE = 401;
const FORBIDDEN_ERROR_CODE = 403;
const NOT_FOUND_CODE = 404;
const CONFLICT_ERROR_CODE = 409;
const INTERNAL_SERVER_ERROR_CODE = 500;

const BAD_REQUEST_CODE_MESSAGE = 'Incorrect data';
const UNAUTHORIZED_ERROR_CODE_MESSAGE = 'Authorization is required';
const FORBIDDEN_ERROR_CODE_MESSAGE = 'Impossible to delete';
const NOT_FOUND_CODE_MESSAGE = 'No data';
const CONFLICT_ERROR_CODE_MESSAGE = 'User already exists';
const INTERNAL_SERVER_ERROR_CODE_MESSAGE = 'Internal Server Error';
const USER_DATA_ERROR_MESSAGE = 'Incorrect password or email';
const PAGE_NOT_FOUND_MESSAGE = 'Page not found';
const LOGIN_SUCCESS_MESSAGE = 'Authorization was successful';
const LOGOUT_MESSAGE = 'Logout complete';
const LIMITER_MESSAGE = 'You have exceeded the request limit';

module.exports = {
  CREATED_CODE,
  BAD_REQUEST_CODE,
  UNAUTHORIZED_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
  NOT_FOUND_CODE,
  CONFLICT_ERROR_CODE,
  INTERNAL_SERVER_ERROR_CODE,
  BAD_REQUEST_CODE_MESSAGE,
  UNAUTHORIZED_ERROR_CODE_MESSAGE,
  FORBIDDEN_ERROR_CODE_MESSAGE,
  NOT_FOUND_CODE_MESSAGE,
  CONFLICT_ERROR_CODE_MESSAGE,
  INTERNAL_SERVER_ERROR_CODE_MESSAGE,
  USER_DATA_ERROR_MESSAGE,
  PAGE_NOT_FOUND_MESSAGE,
  LOGIN_SUCCESS_MESSAGE,
  LOGOUT_MESSAGE,
  LIMITER_MESSAGE,
};
